---
title: "Tergite Frontend"
---

---

## [2025.06.0]
_released on: 16th of June 2025_

### Changed

- BREAKING: Removed v2 from MSS URL in env and docker configs

- MSS 
    - BREAKING: Replaced `requirements.txt` with `pyproject.toml`
    - BREAKING: Upgraded lowest version of python supported to python 3.12
    - BREAKING: Upgraded Fastapi to 0.115.12
    - BREAKING: Upgraded pydantic to the latest v2
    - BREAKING: Removed the v1/auth, v1/backends and v1/jobs endpoints
    - BREAKING: Changed creation of jobs to require a body with required fields 'device' and 'calibration_date'
    - BREAKING: Disabled Mongo-style payloads when updating jobs to ensure more security by reducing capabilities exposed to HTTP
    - BREAKING: Changed job update payloads to only accept the fields that are in the Job schema
    - BREAKING: Changed the POST `/v2/calibrations` endpoint to receive only a single calibration result at a time
    - BREAKING: Changed the GET `/v2/calibrations/` endpoint to return a paginated response of calibrations
    - BREAKING: Made 'calibration_date' a required property on the job object
    - BREAKING: Changed the GET `/v2/me/jobs` endpoint to `/me/jobs/`
    - BREAKING: Changed the GET `/me/jobs` endpoint to return a paginated response of jobs
    - BREAKING: Changed `/v2/` endpoints to `/` endpoints
    - BREAKING: Remove version property from project schema
    - BREAKING: Return paginated response on the GET `/devices/` endpoint
    - BREAKING: Return paginated response on the GET `/auth/providers/` endpoint
    - BREAKING: Change the query param 'domain' on the GET `/auth/providers/` endpoint to 'email_domain'

- Dashboard 
    - Updated API client code to work with new endpoint structure in MSS
    - Updated cypress tests to work with new endpoint structure in MSS
    - Updated schema for devices in the fixtures

### Added

- MSS
    - Added more extensive search capability on the GET `/jobs/` endpoints so that one can search by more fields in the job
    - Added more extensive search capability on the GET `/devices/` endpoints so that one can search by more fields in the devices
    - Added more extensive search capability on the GET `/calibrations/` endpoints so that one can search by more fields in the calibrations
    - Added more extensive search capability on the GET `/auth/providers/` endpoints so that one can search by more fields in the auth providers

---

## [2025.03.1]
_release on: 18th of March 2025_

### Changed

- Changed the backend configurations for the full e2e to run with the new backend configuration files

---

## [2025.03.0]
_release on: 14th of March 2025_

### Added

- Added Full end-to-end testing combining the backend, API and dashboard

- Dashboard:
    - Added dark mode color change on dark mode toggle button click
    - Added a dark mode toggle button on the login page
    - Added a dark mode toggle button on the dashboard page
    - Changed the coloring of the device map chart to use muted connection lines
    - Changed the coloring of the device bar chart to use purple bar lines, and muted axes

### Changed

- MSS:
    - Renamed `quantum_jobs` to `jobs` service
    - Removed the api routes, DTOs and service methods for the old WebGUI project.
- Dashboard:
    - Disabled the "live" switch when creating projects as admin

### Fixed

- Fix project list in nav bar to be only active projects

---

## [2024.12.2]
_released on: 22nd of January 2025_

### Changed

- Raised logging level to WARN in tergite-frontend when app settings are not production
- Removed NETWORK_MODE environment variable in tergite-mss

### Fixed

- Fixed auth openid errors in tergite-mss when auth is disabled


---

## [2024.12.1]
_released on: 20th of December 2024_

### Added

- Dashboard:

    - Added `run-nginx.sh` script to help initialize/update the variables like cookie names
    API urls and the like in docker prebuilt containers.

### Changed

- Updated the Github actions to push the ':latest' tag along side the version tag to docker registry
- Updated `prebuilt-docker-compose.yml` to pick relevant values from the environment as well as
  from `mss-config.toml` for the dashboard docker compose service

### Fixed

- Fixed the 'parent-folder' image not found error in the Github actions for the dashboard


---

## [2024.12.0]
_released on: 11th of December 2024_

### Added

- Added the admin pages for managing user access in the tergite-dashboard app.

    - Added the tokens list page for viewing, editing and deleting tokens of current user
    - Added the projects list page for viewing, requesting QPU time and deleting projects for current user
    - Added admin page for viewing, and approving user requests
    - Added admin page for viewing, editing, deleting and creating new projects
    - Added close button on the job detail drawer on the home page

- Added user access endpoints to the v2 API version of the tergite-mss app.

    - Added GET `/v2/me` endpoint to get current user info
    - Added DELETE `/v2/me/projects/{id}` endpoint to delete project current user administers
    - Added GET `/v2/admin/qpu-time-requests` endpoint to get all user requests to increase QPU seconds on a project
    - Added POST `/v2/admin/qpu-time-requests` endpoint for project members to request for more QPU seconds 
    - Added GET `/v2/admin/user-requests` endpoint for admins to retrieve a list of user requests
    - Added PUT `/v2/admin/user-requests/{id}` endpoint for admins to update (e.g. approve/reject) as user request
    - Added POST `/v2/admin/projects/` endpoint for admins to create a new project
        - Creates new empty user if non-existent emails are passed as user_emails or admin_email
    - Added GET `/v2/admin/projects/` endpoint for admins to retireve a list of projects
    - Added GET `/v2/admin/projects/{id}` endpoint for admins to view a project of given id
    - Added PUT `/v2/admin/projects/{id}` endpoint for admins to update a project of given id
        - Creates new empty user if non-existent emails are passed as user_emails or admin_email
    - Added DELETE `/v2/admin/projects/{id}` endpoint for admins to soft delete a project
    - Added the PUT `/auth/me/app-tokens/{token_id}` endpoint for extending app token's lifetimes
    - Added the PUT `/v2/me/tokens/{token_id}` endpoint for extending app token's lifetimes
    - Added user access endpoints to the v2 API version of the tergite-mss app.

- Added the `MSS_PORT` environment variable to the `.env.example` to configure the port on which tergite-mss runs on in docker compose.
- Added the `NETWORK_MODE` environment variable to the `.env.example` to configure the `network_mode` to use in docker compose file

### Fixed

- tergite-mss 

    - Fixed the not found error when deleting expired app tokens
    - Fixed httpx version to 0.27.2 as 0.28.0 removes many deprecations that we were still dependent on in FastAPI testClient

### Changed 

- tergite-dashboard

    - Changed devices page to show 'no devices found' when no devices are available.
    - Changed to show sidebar placeholder on admin user requests page when no user request is selected

---

## [2024.09.1]
_released on: 24th of September 2024_

### Added

- Added example scopes in the mss_config.example.toml in tergite-mss
- Added units 'Hz' and 's' to calibration data schema

### Fixed

-  Fixed CORS error when dashboard and MSS are on different domains or subdomains
-  Fixed 'AttributeError: 'NoneType' object has no attribute 'resource_usage'' on GET /v2/me/jobs

### Changed

- Removed `archives` folder in tergite-mss
- Removed `dev` folder in tergite-mss
- Changed all calibration v2 properties optional
- Normalized calibration data to have frequencies in GHz and durations in microseconds in the dashboard

---

## [2024.09.0]
_released on: 2nd of September 2024_

### Added

- Added the tergite-dashboard app. It included:
    - Device summary list on the dashboard home
    - Jobs list on the dashboard home
    - Jobs detail drawer on the dashboard home
    - Device list page
    - Device detail page
    - Error page
- Added v2 endpoints on Tergite MSS including
    - `/v2/me/projects/` to `GET`, `POST` current cookie user's projects
    - `/v2/me/projects/{project_id}` to `GET`, `PUT` current cookie user's single project
    - `/v2/me/tokens/` to `GET`, `POST` current cookie user's application tokens
    - `/v2/me/tokens/{token_id}` to `GET`, `PUT` current cookie user's application token
    - `/v2/me/jobs/` to `GET` current cookie user's jobs (with option of specifying project id)
    - `/v2/auth/providers` to `GET` the available Oauth2 provider corresponding to a given email domain
    - `/v2/auth/{provider}/authorize` to `POST` Oauth2 initialization request for given `provider`
    - `/v2/auth/{provider}/callback` to handle `GET` redirects from 3rd party Oauth2 providers after successful login
    - `/v2/auth/logout` to handle `POST` requests to logout the current user via cookies
    - `/v2/calibrations/` to `GET`, `POST` calibration data for all devices. `POST` is available for only system users.
    - `/v2/calibration/{device_name}` to `GET` calibration data for the device of the given `device_name`
    - `/v2/devices` to `GET`, `PUT` (upsert) all devices. `PUT` is available for only system users.
    - `/v2/devices/{name}` to `GET`, `PUT` the device of a given name. `PUT` is available for only system users.

### Changed

- Removed the tergite-landing-page app
- Removed the tergite-webgui app

---

## [2024.04.1]
_released on: 28th of May 2024_

Initial Public Release

### Changed

- Updated the contribution guidelines and government model statements
