---
title: "Tergite SDK"
---

---

## [2025.06.1]
_released on: 17th of June 2025_

### Changed

- Removed unwanted artefacts from the packaged library

### Fixed

- Made cleanup in e2e fault tolerant

---

## [2025.06.0]
_released on: 16th of June 2025_

### Added

- Implemented job cancellation

### Changed

- BREAKING: Changed the MSS endpoints `/v2/devices` to `/devices`
- BREAKING: Changed the MSS endpoints `/v2/calibrations` to `/calibrations`
- BREAKING: Changed the expected Device info schema to include 'number_of_resonators' and 'number_of_couplers'
- Added pydantic as an explicit dependency
- Moved completely from dataclasses to pydantic models
- Set the minimum permitted python to 3.12
- Removed the `tergite.qiskit` package and moved everything to the `tergite` package
- Removed the `tergite.qiskit.providers` package and moved everything to the parent package
- Raise `QiskitBackendNotFoundError` when malformed backend is returned in data instead of `TypeError`
- BREAKING: Remove `extras` from `AccountInfo`
- BREAKING: Change signature of `Tergite.use_provider_account(account, save)` to `Tergite.use_provider_account(service_name, url, token, save)`


---

## [2025.03.0]
_released on: 14th of March 2025_

### Changed

- Refactor: Changed a few error messages to include the original error
- Refactor: Changed the Job metadata to always be generated on the backend.  
  It was originally setting them both on the backend and the SDK.
- Upgraded to Poetry > 2.1

### Added

- Added caching of calibration requests to reduce number of calls to remote API
- Added caching on Job's `status()`, `result()`, `download_url` to reduce number of calls to remote API
- Added sending of `calibration_date` (str) query parameter during job registration.
- Added end-to-end tests for `qiskit_pulse_1q` simulator backend
- Added end-to-end tests for `qiskit_pulse_2q` simulator backend
- Added Gitlab and Github CI configurations for end-to-end tests

---

## [2024.12.1]
_released on: 18th of December 2024_

### Changed

- Updated tests to run tests against multiple backends
- Updated `Provider.job()` to return a `Job` instance without an upload_url

### Fixed

- Fixed the error 'Coupling (0, 0) not a coupling map' for backends without couplers

---

## [2024.12.0]
_released on: 11th of December 2024_

### Added

- Added the `job()` method to provider to retrieve job by job ID
- Added functionality to get control channel index given qubit tuple
- Added two qubit CZ gate functionality 

### Changed

- Upgraded Qiskit version to 1.0+, <1.3
- Use MSS v2 endpoints for backend and calibration data

---

## [2024.09.0]
_released on: 16th of September 2024_

- No change

---

## [2024.04.1]
_released on: 29th of May 2024_

Initial Public Release

### Changed

- Changed README.rst to README.md
- Changed CONTRIBUTING.rst to CONTRIBUTING.md
- Changed CREDITS.rst to CREDITS.md
- Updated the contribution guidelines and government model statements
