---
title: "Tergite Autocalibration"
---

---

## [2025.12.0] - 2026-03-16
_released on 16th of March 2026_

### Added

- Backup functions for redis storage
- Motzoi parameter for DRAG pulse in tergite SDK
- CLI endpoint for automatic mixer calibration

### Changed

- Removed development folder (can still be accessed in the git history)
- Replaced MSS update script with BCC calibration seed script
- Refactored CZ Parametrization node
- Added CZ Chevron node
- Added CZ local phases node
- Removed quickstart endpoint
- Moved scripts that handle SPI operations to the CLI
- Cleanup of the BaseNode
- Interface for measurement types
- Wizard for the hardware configuration

### Fixed

- Fixes in the n_rabi_12_oscillations
- Improvements in how coupler data is loaded from redis
- Cleanup unused scripts and modules

## [2025.09.0] - 2025-09-16
_released on 16th of September 2025_

### Added

- Datasets from IQT Nordics

### Changed

- Data browser uses plotly instead of PyQT and integrates better with CLI
- Run single calibration node in re-analysis
- Migrated documentation from Quarto to MkDocs Material.

### Fixed

- Simplify GitLab pipeline

---

## [2025.06.0]
_released on 16th of June 2025_

### Added

- Better labelling for the analysis output plots

### Changed

- Upgrade Python to version 3.12
- Migration from poetry to setuptools
- Make external samplespace multidimensional

### Fixed

- Reduced the packaged library size to below pypi's limit by using a `MANIFEST.in` file

---

## [2025.03.0]
_released on 16th of March 2025_

### Added
- Advanced logging
- Debugging endpoint
- Quickstart endpoint to generate templates semi-automatically

### Changed

- Rename all node class names to camel case
- Re-analysis is more user-friendly
- Make pipeline more modular
- Improved node documentation

---

## [2024.12.0]
_released on 12th of December 2024_

### Added

- Dataset browser
- ScheduleNode and ExternalParameterSweepNode as subclasses of BaseNode
- DeviceManager class

### Changed

- Migrated cli from click to typer
- Switch to quantify-scheduler version 0.21.2
- Switch to qblox-instruments version 0.14.1 (qblox-firmware should be 9.0.1)
- Upgrade to Python version 3.10

---

## [2024.09.0]
_released on 16th of September 2024_

### Added

- Redis storage manager

### Changed

- Switch to quantify-scheduler version 0.20.0

---

## [2024.04.0]
_released on 29th of May 2024_

Initial Public Release

### Added

- All research-related features regarding the calibration of a CZ gate
- Updater to push calibration values as a backend to MSS/database

### Changed

- Improved command line interface
- Renamed from tergite-acl to tergite-autocalibration
- Updated the contribution guidelines and government model statements
